# rbac-readonly.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: developer-readonly-binding
subjects:
- kind: User
  name: arn:aws:iam::919113286163:user/eks-developer-readonly   
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view   
  apiGroup: rbac.authorization.k8s.io


